name: Build Installers
on:
  workflow_dispatch: # This adds the manual "Run workflow" button
## on: [push]

jobs:
  # --- Windows Job ---
  # latest version: Windows 11
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run jpackage for Windows
        run: jpackage "@jpkWindows.txt"

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Windows/*.exe

  # --- Linux Job ---
  # latest version: 26.04 LTS, codenamed "Resolute Raccoon"
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y fakeroot

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run jpackage for Linux
        run: jpackage @jpkLinux.txt

      - name: Upload Linux Installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: Linux/*.deb

# --- macos job ---
  build-macos:
    strategy:
      matrix:
        # Build for both Intel (x86_64) and Apple Silicon (arm64)
        include:
          # - arch: intel (maybe someday I will use this architecture too)
          #  runner: macos-15 # Standard Intel runner
          - arch: silicon
            runner: macos-latest # Standard Apple Silicon runner
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run jpackage for macOS
        # No change needed here if your @jpkMacOSX.txt is generic;
        # jpackage will use the architecture of the runner it's on.
        run: jpackage @jpkMacOSX.txt

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          # Separate the files so you know which is which
          name: macOS-${{ matrix.arch }}-installer
          path: MacOSX/*.dmg