name: Build Installers
on:
  workflow_dispatch: # This adds the manual "Run workflow" button
## on: [push]

jobs:
  # --- Windows Job ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run jpackage for Windows
        run: jpackage "@jpkWindows.txt"

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Windows/*.exe

  # --- Linux Job ---
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y fakeroot

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run jpackage for Linux
        run: jpackage @jpkLinux.txt

      - name: Upload Linux Installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: Linux/*.deb

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run jpackage for macOS
        run: jpackage @jpkMacOSX.txt

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-installer
          path: MacOSX/*.dmg
